const quotes = [{
            id: '10-2500x1667.jpeg',
            title: 'ocean-view 2',
            description: 'portrait photo',
            width: 640,
            height: 853,
            pathURL: 'assets/10-2500x1667.jpeg',
            linkURL: 'https://i.picsum.photos/id/10/2500/1667.jpg?hmac=J04WWC_ebchx3WwzbM-Z4_KC_LeLBWr5LZMaAkWkF68',
            credit: 'pual Jarvis',
            creditURL: 'https://picsum.photos/images#2',
        },
        {
            id: '13-2500x1667.jpeg',
            title: 'Ocean-view 2',
            description: 'portrait photo-2',
            width: 640,
            height: 960,
            pathURL: '"assets/1038-3914x5863.jpeg',
            linkURL: 'https://i.picsum.photos/id/1038/3914/5863.jpg?hmac=SGtXryWDkn_eVQdA1NjYrikcsrIfcfS4SFYHo4lCpkQ',
            credit: '',
            creditURL: 'https://picsum.photos/images#2',
        },
        {
            id: '1065-3744x5616.jpeg',
            title: 'ocean-view-3',
            description: 'portrait photo-3',
            width: 640,
            height: 959,
            pathURL: 'assets/1065-3744x5616.jpeg',
            linkURL: 'https://i.picsum.photos/id/1047/3264/2448.jpg?hmac=ksy0K4uGgm79hAV7-KvsfHY2ZuPA0Oq1Kii9hqkOCfU',
            credit: 'Alex Topolyansky',
            creditURL: 'https://picsum.photos/images#2',
        },
        {
            id: 'Lake falling',
            title: 'ocean-view-4',
            description: 'portrait photo-4',
            width: 640,
            height: 959,
            pathURL: 'assets/12-2500x1667.jpeg',
            linkURL: 'https://i.picsum.photos/id/1018/3914/2935.jpg?hmac=3N43cQcvTE8NItexePvXvYBrAoGbRssNMpuvuWlwMKg',
            credit: 'Andrew Ridley',
            creditURL: 'https://picsum.photos/images',
        },
        {
            id: '1025-6000x4000',
            title: 'ocean-view-5',
            description: 'portrait photo-5',
            width: 640,
            height: 960,
            pathURL: 'assets/1025-6000x4000.jpeg',
            linkURL: 'https://i.picsum.photos/id/1018/3914/2935.jpg?hmac=3N43cQcvTE8NItexePvXvYBrAoGbRssNMpuvuWlwMKg',
            credit: 'Betrand Zuchuat',
            creditURL: 'https://picsum.photos/images',
        },
        {
            id: 'beach',
            title: 'ocean-view',
            description: 'portrait photo-6',
            width: 640,
            height: 959,
            pathURL: 'assets/1065-3744x5616.jpeg',
            linkURL: 'https://images.pexels.com/photos/6185361/pexels-photo-6185361.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
            credit: 'Marcelo Quinan',
            creditURL: 'https://www.pexels.com/@polina-kovaleva',
        },
        {
            id: 'beautiful view',
            title: 'You are an amazing human',
            description: 'portrait photo-7',
            width: 640,
            height: 960,
            pathURL: 'assets/13-2500x1667.jpeg',
            linkURL: 'Pual Jarvis',
            credit: 'sergee bee',
            creditURL: 'https://www.pexels.com/@fotios-photos',
        },
        {